const data = [
  {
    name: 'C.H.A.N.D.L.E.R',
    description: '',
    phrase: '"Could I be more me?"',
    funny: 90,
    beauty: 85,
    friendship: 90,
    image: 'https://i.pinimg.com/originals/d5/43/b1/d543b156dcb4d039273fe3628f4fae23.jpg',
    rare: 'normal',
    trunfo: false,
  },
  {
    name: 'J.O.E.Y',
    description: '',
    phrase: '"How you doing?"',
    funny: 90,
    beauty: 90,
    friendship: 90,
    image: 'https://64.media.tumblr.com/d0509a4d50d2fd48d9279ad435e5f601/tumblr_pk1lccpcEA1uns10qo1_1280.jpg',
    rare: 'normal',
    trunfo: false,
  },
  {
    name: 'R.O.S.S',
    description: '',
    phrase: '"Unagi"',
    funny: 80,
    beauty: 75,
    friendship: 70,
    image: 'https://i.pinimg.com/originals/1d/c2/af/1dc2af94a2214240a46c41a85a76b88e.jpg',
    rare: 'normal',
    trunfo: false,
  },
  {
    name: 'P.H.O.E.B.E',
    description: '',
    phrase: '"My eyess"',
    funny: 90,
    beauty: 85,
    friendship: 75,
    image: 'https://i.pinimg.com/originals/14/6a/d1/146ad13c64070d1909e38c6a5b009756.jpg',
    rare: 'normal',
    trunfo: false,
  },
  {
    name: 'M.O.N.I.C.A',
    description: '',
    phrase: '"I know!!!"',
    funny: 75,
    beauty: 90,
    friendship: 80,
    image: 'https://i.pinimg.com/736x/83/22/7e/83227ea870acba628aed6d0e45a17dc5.jpg',
    rare: 'normal',
    trunfo: false,
  },
  {
    name: 'R.A.C.H.E.L',
    description: '',
    phrase: '"No uterus, no opinion"',
    funny: 80,
    beauty: 90,
    friendship: 80,
    image: 'https://i.pinimg.com/originals/4f/d8/3d/4fd83d4782cc658c330641b0e58051f1.jpg',
    rare: 'normal',
    trunfo: false,
  },
  // {
  //   name: 'Beavis & Butthead',
  //   description: '2 adolescentes socialmente incompetentes e sem escrúpulos morais',
  //   funny: 90,
  //   attr2: 60,
  //   attr3: 0,
  //   image: 'https://www.thesoundarchive.com/images/Tiles/beavis-and-butthead.png',
  //   rare: 'muito raro',
  //   trunfo: false,
  // },
  // {
  //   name: 'Stan Smith',
  //   description: 'Um imprudente e insensível agente da CIA. Republicano conservador',
  //   attr1: 65,
  //   attr2: 45,
  //   attr3: 45,
  //   image: 'https://p1.sa123.cc/wwlsj_tzq/TVi7TslTUxsmiSVRc9bupxC20PRPakWGM9CQnOIP7GKOOKwxqTGmGYdhzzbnm511B37bOgb1x80AvdXmoDY6KleA.jpg',
  //   rare: `muito rar${'o'}`,
  //   trunfo: false,
  // },
  // {
  //   name: 'Eric Cartman',
  //   description: 'Uma criança de 8 anos impulsiva, egocêntrica e com ossos grandes',
  //   attr1: 55,
  //   attr2: 5,
  //   attr3: 65,
  //   image: 'https://cdn.shopify.com/s/files/1/0170/5859/4880/files/cartmanOverlay_1980x.png?v=1580498406',
  //   rare: 'raro',
  //   trunfo: false,
  // },
];

export default data;
